# These are supported funding model platforms

github: [shy-anchovy] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: shy-anchovy # Replace with a single Patreon username
open_collective: shy-anchovy # Replace with a single Open Collective username
ko_fi: shy-anchovy # Replace with a single Ko-fi username
tidelift:  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: shy-anchovy # Replace with a single Liberapay username
issuehunt: shy-anchovy # Replace with a single IssueHunt username
otechie: shy-anchovy # Replace with a single Otechie username
custom: ["https://shyptr.cn",shyptr.cn] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
